---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/cert-manager.io/certificate_v1.json
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: rack-ac-dev
spec:
  dnsNames: ["${SECRET_DOMAIN}", "*.${SECRET_DOMAIN}"]
  duration: 160h
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  privateKey:
    algorithm: ECDSA
    size: 256
    rotationPolicy: Always
  secretName: rack-ac-tls
  usages:
    - digital signature
